spring:
  security:
    oauth2:
      client:
        registration:
          pushitdown:
            provider: authserver-provider
            client-id: pushitdown
            client-secret: pushitdown
            authorization-grant-type: authorization_code
            redirect-uri: "http://client.local:8080/login/oauth2/code/pushitdown"
            scope: openid, profile
        provider:
          authserver-provider:
            issuer-uri: http://auth-server.local:9000
            authorization-uri: http://auth-server.local:9000/oauth2/authorize
            token-uri: http://auth-server.local:9000/oauth2/token
            user-name-attribute: sub